#!/bin/bash

rm -f /etc/sudoers.d/user-nopasswd

cat << EOF > /etc/sudoers.d/user-nopasswd
user ALL=(ALL) NOPASSWD:ALL
EOF

# ln -s /media/psf/workspace /home/user/

apt install --upgrade -y \
    docker-compose \
    docker.io \
    finger \
    jadx \
    ldap-utils \
    mdk4 \
    meld \
    python3-pyqt5 \
    python3-sqlalchemy \
    realtek-rtl88xxau-dkms \
    routersploit \
    rsh-client \
    rwho \
    ssh-audit \
    tilix \
    wkhtmltopdf \
    x11-apps \


rm -fR /tmp/sparta /usr/share/sparta
git clone --depth 1 https://github.com/secforce/sparta.git /tmp/sparta
mv /tmp/sparta /usr/share/sparta
mv /usr/share/sparta/sparta /usr/bin/sparta
chmod +x /usr/bin/sparta

pip3 install certipy-ad


# apt install --upgrade -y budgie-desktop
# su user
# panel=$(python3 -c "a=`dconf read /com/solus-project/budgie-panel/panels`; print(a[0], end='')")

# dconf read /com/solus-project/budgie-panel/panels/\{${panel}\}/location
# dconf write /com/solus-project/budgie-panel/panels/\{${panel}\}/location "'top'"

su user

dconf write /org/gnome/shell/extensions/dash-to-dock/dock-position "'LEFT'"
dconf write /org/gnome/shell/extensions/dash-to-dock/dock-fixed true
dconf write /org/gnome/shell/extensions/dash-to-dock/extend-height true
dconf write /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size 24

exit 
